apiVersion: iam.upbound.io/v1alpha1
kind: Token
metadata:
  name: access-token
spec:
  forProvider:
    name: access-token
    owner:
      type: robots
      idRef:
        name: serviceaccount
  writeConnectionSecretToRef:
    name: up-access-token
    namespace: upbound-system